import electrified from '@/assets/main-page/menu-electrified.png'
import bmwm from '@/assets/main-page/menu-bmwm.png'
import vehiclePhoto from '@/assets/main-page/bmw4.webp'

export const menuText = [
  {
    firstLevel: {
      name: 'Models',
      secondLevel: [
        {
          name: 'All Models',
          thirdLevel: [
            { name: 'X1', link: '#', image: vehiclePhoto },
            { name: 'X3', link: '#', image: vehiclePhoto },
            { name: 'X4', link: '#', image: vehiclePhoto },
            { name: 'X5', link: '#', image: vehiclePhoto },
            { name: 'X6', link: '#', image: vehiclePhoto },
            { name: 'X7', link: '#', image: vehiclePhoto },
            { name: '2', link: '#', image: vehiclePhoto },
            { name: '3', link: '#', image: vehiclePhoto },
            { name: '4', link: '#', image: vehiclePhoto },
            { name: '5', link: '#', image: vehiclePhoto },
            { name: '6', link: '#', image: vehiclePhoto },
            { name: '7', link: '#', image: vehiclePhoto },
            { name: 'Z4', link: '#', image: vehiclePhoto },
            { name: 'M Model', link: '#', image: vehiclePhoto },
            { name: 'iX', link: '#', image: vehiclePhoto },
            { name: 'i4', link: '#', image: vehiclePhoto },
            { name: 'i5', link: '#', image: vehiclePhoto },
            { name: 'i7', link: '#', image: vehiclePhoto },
            { name: 'XM', link: '#', image: vehiclePhoto },
          ],
        },
        {
          name: 'SUVs',
          thirdLevel: [
            { name: 'X1', link: '#', image: vehiclePhoto },
            { name: 'X3', link: '#', image: vehiclePhoto },
            { name: 'X4', link: '#', image: vehiclePhoto },
            { name: 'X5', link: '#', image: vehiclePhoto },
            { name: 'X6', link: '#', image: vehiclePhoto },
            { name: 'X7', link: '#', image: vehiclePhoto },
            { name: '2', link: '#', image: vehiclePhoto },
            { name: '3', link: '#', image: vehiclePhoto },
            { name: '4', link: '#', image: vehiclePhoto },
            { name: '5', link: '#', image: vehiclePhoto },
            { name: '6', link: '#', image: vehiclePhoto },
            { name: '7', link: '#', image: vehiclePhoto },
            { name: 'Z4', link: '#', image: vehiclePhoto },
            { name: 'M Model', link: '#', image: vehiclePhoto },
            { name: 'iX', link: '#', image: vehiclePhoto },
            { name: 'i4', link: '#', image: vehiclePhoto },
            { name: 'i5', link: '#', image: vehiclePhoto },
            { name: 'i7', link: '#', image: vehiclePhoto },
            { name: 'XM', link: '#', image: vehiclePhoto },
          ],
        },
        {
          name: 'Sedans',
          thirdLevel: [
            { name: 'X1', link: '#', image: vehiclePhoto },
            { name: 'X3', link: '#', image: vehiclePhoto },
            { name: 'X4', link: '#', image: vehiclePhoto },
            { name: 'X5', link: '#', image: vehiclePhoto },
            { name: 'X6', link: '#', image: vehiclePhoto },
            { name: 'X7', link: '#', image: vehiclePhoto },
            { name: '2', link: '#', image: vehiclePhoto },
            { name: '3', link: '#', image: vehiclePhoto },
            { name: '4', link: '#', image: vehiclePhoto },
            { name: '5', link: '#', image: vehiclePhoto },
            { name: '6', link: '#', image: vehiclePhoto },
            { name: '7', link: '#', image: vehiclePhoto },
            { name: 'Z4', link: '#', image: vehiclePhoto },
            { name: 'M Model', link: '#', image: vehiclePhoto },
            { name: 'iX', link: '#', image: vehiclePhoto },
            { name: 'i4', link: '#', image: vehiclePhoto },
            { name: 'i5', link: '#', image: vehiclePhoto },
            { name: 'i7', link: '#', image: vehiclePhoto },
            { name: 'XM', link: '#', image: vehiclePhoto },
          ],
        },
        {
          name: 'Coupes',
          thirdLevel: [
            { name: 'X1', link: '#', image: vehiclePhoto },
            { name: 'X3', link: '#', image: vehiclePhoto },
            { name: 'X4', link: '#', image: vehiclePhoto },
            { name: 'X5', link: '#', image: vehiclePhoto },
            { name: 'X6', link: '#', image: vehiclePhoto },
            { name: 'X7', link: '#', image: vehiclePhoto },
            { name: '2', link: '#', image: vehiclePhoto },
            { name: '3', link: '#', image: vehiclePhoto },
            { name: '4', link: '#', image: vehiclePhoto },
            { name: '5', link: '#', image: vehiclePhoto },
            { name: '6', link: '#', image: vehiclePhoto },
            { name: '7', link: '#', image: vehiclePhoto },
            { name: 'Z4', link: '#', image: vehiclePhoto },
            { name: 'M Model', link: '#', image: vehiclePhoto },
            { name: 'iX', link: '#', image: vehiclePhoto },
            { name: 'i4', link: '#', image: vehiclePhoto },
            { name: 'i5', link: '#', image: vehiclePhoto },
            { name: 'i7', link: '#', image: vehiclePhoto },
            { name: 'XM', link: '#', image: vehiclePhoto },
          ],
        },
        {
          name: 'Convertibles',
          thirdLevel: [
            { name: 'X1', link: '#', image: vehiclePhoto },
            { name: 'X3', link: '#', image: vehiclePhoto },
            { name: 'X4', link: '#', image: vehiclePhoto },
            { name: 'X5', link: '#', image: vehiclePhoto },
            { name: 'X6', link: '#', image: vehiclePhoto },
            { name: 'X7', link: '#', image: vehiclePhoto },
            { name: '2', link: '#', image: vehiclePhoto },
            { name: '3', link: '#', image: vehiclePhoto },
            { name: '4', link: '#', image: vehiclePhoto },
            { name: '5', link: '#', image: vehiclePhoto },
            { name: '6', link: '#', image: vehiclePhoto },
            { name: '7', link: '#', image: vehiclePhoto },
            { name: 'Z4', link: '#', image: vehiclePhoto },
            { name: 'M Model', link: '#', image: vehiclePhoto },
            { name: 'iX', link: '#', image: vehiclePhoto },
            { name: 'i4', link: '#', image: vehiclePhoto },
            { name: 'i5', link: '#', image: vehiclePhoto },
            { name: 'i7', link: '#', image: vehiclePhoto },
            { name: 'XM', link: '#', image: vehiclePhoto },
          ],
        },
        {
          name: 'Electrified',
          image: electrified,
          isSpacial: true,
          thirdLevel: [
            { name: 'X1', link: '#', image: vehiclePhoto },
            { name: 'X3', link: '#', image: vehiclePhoto },
            { name: 'X4', link: '#', image: vehiclePhoto },
            { name: 'X5', link: '#', image: vehiclePhoto },
            { name: 'X6', link: '#', image: vehiclePhoto },
            { name: 'X7', link: '#', image: vehiclePhoto },
            { name: '2', link: '#', image: vehiclePhoto },
            { name: '3', link: '#', image: vehiclePhoto },
            { name: '4', link: '#', image: vehiclePhoto },
            { name: '5', link: '#', image: vehiclePhoto },
            { name: '6', link: '#', image: vehiclePhoto },
            { name: '7', link: '#', image: vehiclePhoto },
            { name: 'Z4', link: '#', image: vehiclePhoto },
            { name: 'M Model', link: '#', image: vehiclePhoto },
            { name: 'iX', link: '#', image: vehiclePhoto },
            { name: 'i4', link: '#', image: vehiclePhoto },
            { name: 'i5', link: '#', image: vehiclePhoto },
            { name: 'i7', link: '#', image: vehiclePhoto },
            { name: 'XM', link: '#', image: vehiclePhoto },
          ],
        },
        {
          name: 'BMW M',
          image: bmwm,
          isSpacial: true,
          thirdLevel: [
            { name: 'X1', link: '#', image: vehiclePhoto },
            { name: 'X3', link: '#', image: vehiclePhoto },
            { name: 'X4', link: '#', image: vehiclePhoto },
            { name: 'X5', link: '#', image: vehiclePhoto },
            { name: 'X6', link: '#', image: vehiclePhoto },
            { name: 'X7', link: '#', image: vehiclePhoto },
            { name: '2', link: '#', image: vehiclePhoto },
            { name: '3', link: '#', image: vehiclePhoto },
            { name: '4', link: '#', image: vehiclePhoto },
            { name: '5', link: '#', image: vehiclePhoto },
            { name: '6', link: '#', image: vehiclePhoto },
            { name: '7', link: '#', image: vehiclePhoto },
            { name: 'Z4', link: '#', image: vehiclePhoto },
            { name: 'M Model', link: '#', image: vehiclePhoto },
            { name: 'iX', link: '#', image: vehiclePhoto },
            { name: 'i4', link: '#', image: vehiclePhoto },
            { name: 'i5', link: '#', image: vehiclePhoto },
            { name: 'i7', link: '#', image: vehiclePhoto },
            { name: 'XM', link: '#', image: vehiclePhoto },
          ],
        },
      ],
    },
  },
  {
    firstLevel: {
      name: 'Build Your Own',
    },
  },
  {
    firstLevel: {
      name: 'Shopping',
    },
  },
  {
    firstLevel: {
      name: 'BMW Electric',
    },
  },
  {
    firstLevel: {
      name: 'Owners',
    },
  },
]
